
// Generated by https://quicktype.io

import { User } from "./user.interface";

export interface LoginResponse {
  success: boolean;
  message: string;
  user:    User;
  token:   string;
  error?:  string;
  status?: number;
}



export interface AuthResponse {
  refresh: string;
  access: string;
  user: UserA;
}

export interface UserA {
  id_usuario: number;
  name_user: string;
  email: string;
  creation_date: string; // Puedes cambiarlo a Date si prefieres trabajar con objetos Date
  is_staff: boolean;
  is_superuser: boolean;
  is_active: boolean;
}
